<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManagePlanes.aspx.cs" Inherits="Rom_Airlines.ManagePlanes" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <div style="text-align: center">
    
        <h1>
            Manage Planes</h1>
    
    </div>
    <asp:GridView ID="GridPlanes" runat="server" style="text-align: center" 
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
                OnRowEditing="GridPlanes_RowEditing" OnRowDeleting="GridPlanes_RowDeleting">
    </asp:GridView>
    </form>
</body>
</html>
