<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManagePlaneModel.aspx.cs" Inherits="Rom_Airlines.ManagePlaneModel" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
    <style type="text/css">
        .style1
        {
            text-align: right;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div style="text-align: center">
    
        <h1>
            Manage Plane Models</h1>
    
    </div>
    <div style="text-align: center">
    
        <div class="style1">
    
                <asp:LinkButton ID="menuButton" runat="server" BorderStyle="Outset" 
                    CausesValidation="False" Font-Bold="True" Font-Overline="False" 
                    Font-Strikeout="False" PostBackUrl="~/menu.aspx">Menu</asp:LinkButton>
    </div>
    
        <p>
            <asp:GridView ID="GridPlaneModel" runat="server" 
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
                OnRowEditing="GridPlaneModel_RowEditing" OnRowDeleting="GridPlaneModel_RowDeleting">
            </asp:GridView>
        </p>
    
    </div>
    </form>
</body>
</html>
