<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManagePlaneModel.aspx.cs" Inherits="Rom_Airlines.ManagePlaneModel" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <div style="text-align: center">
    
        <h1>
            Manage Plane Models</h1>
    
    </div>
    <div style="text-align: center">
    
        <p>
            <asp:GridView ID="GridPlaneModel" runat="server" 
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
                OnRowEditing="GridPlaneModel_RowEditing" OnRowDeleting="GridPlaneModel_RowDeleting">
            </asp:GridView>
        </p>
    
    </div>
    </form>
</body>
</html>
