<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageLicences.aspx.cs" Inherits="Rom_Airlines.ManageLicences" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
    <style type="text/css">
        #form1
        {
            text-align: center;
        }
        .style1
        {
            text-align: right;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
    <h1 style="text-align: center">
        Manage Licences</h1>
        
        <div class="style1">
    
                <asp:LinkButton ID="menuButton" runat="server" BorderStyle="Outset" 
                    CausesValidation="False" Font-Bold="True" Font-Overline="False" 
                    Font-Strikeout="False" PostBackUrl="~/menu.aspx">Menu</asp:LinkButton>
    </div>
    <asp:GridView ID="GridLicences" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" style="text-align: center"
        OnRowEditing="GridLicences_RowEditing" OnRowDeleting="GridLicences_RowDeleting">
    </asp:GridView>
    <br />
    <asp:Label ID="Label1" runat="server" Text="Licence Name"></asp:Label>
    <asp:TextBox ID="TextBox1" runat="server"  
        style="text-align: center" ValidationGroup="ml"></asp:TextBox>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
        ControlToValidate="TextBox1" Display="Dynamic" 
        ErrorMessage="RequiredFieldValidator" ValidationGroup="ml">*</asp:RequiredFieldValidator>
    <asp:Button ID="Button1" runat="server" style="text-align: center" 
        Text="Add Licence" onclick="Button1_Click" ValidationGroup="ml" />
    <br />
    </form>
</body>
</html>
