<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageAirport.aspx.cs" Inherits="Rom_Airlines.ManageAirport" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
    <style type="text/css">
        #form1
        {
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div style="text-align: center">
    
        <h1>
            Manage Airports</h1>
    
    </div>
    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    <asp:Button ID="Button1" runat="server" onclick="Button1_Click" Text="Search" />
    <br />
    <asp:GridView ID="GridAirports" runat="server" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
        OnRowEditing="GridAirports_RowEditing" OnRowDeleting="GridAirports_RowDeleting">
    </asp:GridView>
    </form>
</body>
</html>
