<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageFlight.aspx.cs" Inherits="Rom_Airlines.ManageFlight" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
    <style type="text/css">
        .style1
        {
            width: 100%;
        }
    </style>
</head>
<body style="text-align: center">
    <form id="form1" runat="server">
    <div style="text-align: center">
    
        <h1>
            Manage Flights</h1>
    
    </div>
    <table class="style1">
    <tr>
            <td align="right">
                <asp:LinkButton ID="menuButton" runat="server" BorderStyle="Outset" 
                    CausesValidation="False" Font-Bold="True" Font-Overline="False" 
                    Font-Strikeout="False" PostBackUrl="~/menu.aspx">Menu</asp:LinkButton>
            </td>
        </tr>
        <tr>
            <td>
                <asp:GridView ID="GridFlights" runat="server" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" OnRowEditing="GridFlights_RowEditing"
                    OnRowDeleting="GridFlights_RowDeleting">
                </asp:GridView>
                <br />
                <asp:LinkButton ID="LinkButton1" runat="server" onclick="LinkButton1_Click">Add 
                Flight</asp:LinkButton>
            </td>
        </tr>
    </table>
    </form>
</body>
</html>
